---
version: "2.1"
services:
  duplicati:
    image: linuxserver/duplicati
    container_name: duplicati
    environment:
      - PUID=1000 # user: abc
      - PGID=1000
      - TZ=Europe/Moscow
      - CLI_ARGS= #optional
    volumes:
      - ./config:/config
      - /var/Backups:/backups
      - /var/www:/source
    ports:
      - 8200:8200
    restart: always